# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Andrés Hoyos-Idrobo
email: ahoyosidrobo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Senior Research Scientist at Rakuten Group, Inc. in Paris. Deep learning to
    rank at scale, search relevance, optimal transport, causal inference.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ahoyosid.github.io" # the base hostname & protocol for your site
twitter_username: ahoyosid 
github_username:  ahoyosid


plugins:
    - jekyll-redirect-from
    - jekyll-seo-tag
    - jekyll-sitemap

# Used by jekyll-seo-tag for link previews and structured data
lang: en
author: Andrés Hoyos-Idrobo
logo: /img/ahoyosid.jpg
twitter:
    username: ahoyosid
    card: summary
social:
    name: Andrés Hoyos-Idrobo
    links:
        - https://orcid.org/0000-0003-1729-1927
        - https://scholar.google.com/citations?user=J3344dQAAAAJ
        - https://github.com/ahoyosid
        - https://www.linkedin.com/in/andres-hoyos-idrobo-85b42024
        - https://twitter.com/ahoyosid

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
    input: GFM
    syntax_highlighter: rouge

defaults:
-
    scope:
        path: "" # an empty string here means all files in the project
        type: "pages" # previously `post` in Jekyll 2.2.
    values:
        layout: "page"
-
    scope:
        path: ""
    values:
        image: /img/ahoyosid.jpg



exclude:
    - Gemfile
    - Gemfile.lock
    - README.md
    - LICENSE
    - vendor
